### ISSUE TITLE
Load wallet 

### ISSUE THREAD

**Issue by Masoud-garazhian** [badhitman/Electrum-JSONRPC#1]
how do u load wallet or run daemon ?!

**Comment by badhitman** [comment]
Good afternoon. Is the problem solved? Launching a daemon of what kind? For example, running the Electrum daemon is beyond the scope of this development (properly configuring and running the Electrum deamon wallet is a separate story). I can only suggest that Electrum daemon worked only under Linux. Under Win, it was launched and the process existed, but for some reason there were no responses to the api.If you are trying to run this development as a daemon on .net core, then this is a separate story.
