### ISSUE TITLE
do a transaction

### ISSUE THREAD

**Issue by Masoud-garazhian** [badhitman/Electrum-JSONRPC#2]
hey there 
i wanna do a pay ( transaction ) I don't know  which method I should to do this

**Comment by badhitman** [comment]
Hello. Are you familiar with the work of btc/blockchain in general or Electrum wallet in particular? What does your question relate to? Which of these areas does the question relate to? 

P.S. I hope you use [free faucet coins](https://www.google.com/search?q=bitcoin+faucet) for development?
